modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
showAsResourcePack = false

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "assets/velthoric/velthoric_icon.png"

# Mixin configuration for your mod
[[mixins]]
config = "velthoric.mixins.json"

[[mixins]]
config = "vx-events.mixins.json"

# Dependencies for this mod
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "architectury"
mandatory = true
versionRange = ">=${architectury_api_version}"
ordering = "AFTER"
side = "BOTH"